"""
Django settings for paycrm project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
import datetime
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qy_9!ausa-$*pd90t2ina4g75snknd5ezc=tz)tnynd1gkzu^j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dipay.apps.DipayConfig',
    'rbac.apps.RbacConfig',
    'stark.apps.StarkConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'rbac.middleware.RbacMiddleWare',
]

ROOT_URLCONF = 'paycrm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'paycrm.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',  # .mysql数据库 系统默认sqllite
#         'HOST': 'bdm818511667.my3w.com',   #主机
#         'PORT': 3306,                      #端口
#         'USER':'bdm818511667',
#         'PASSWORD':'wong&85782458nn',
#         'NAME': 'bdm818511667_db',     #数据库名
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # .mysql数据库 系统默认sqllite
        'HOST': '0.0.0.0',  # 主机
        'PORT': 3306,  # 端口
        'USER': 'root',
        'PASSWORD': '123',
        'NAME': 'paycrm',  # 数据库名
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = '/paycrmstatic/'

# STATICFILES_DIRS = []   # 静态文件存储路径

#  客户上传下载文件存储路径
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AVATAR_CHOICES = ['fa-beer', 'fa-archive', 'fa-coffee', 'fa-diamond', 'fa-envelope-o',
                  'fa-flag', 'fa-mortar-board', 'fa-tags', 'fa-tree', 'fa-star', 'fa-share-alt',
                  'fa-university', 'fa-bar-chart', 'fa-th-large', 'fa-gg', 'fa-train', 'fa-tty',
                  'fa-user-plus', 'fa-tv', 'fa-umbrella', 'fa-thumb-tack', 'fa-pie-chart', 'fa-shopping-bag',
                  'fa-lemon-o', 'fa-download', 'fa-cube', 'fa-cog', 'fa-truck']

##################  RBAC 设置 ###############
RBAC_USER_MODLE_CLASS = 'dipay.models.UserInfo'
LOGIN_KEY = 'sflajlfanf'
# 权限在Session中存储的key
PERMISSION_KEY = 'fankmfouifang'
# 菜单在Session中存储的key
MENU_LIST_KEY = '89ljfaljfa8fa-fa'

# 不需要登录，也不需要授权的权限
WHITE_URL_LIST = [
    '/login/',
    '/admin/.*',
]

# 需要登录，不需要特殊授权的权限
NO_PERMISSION_LIST = [
    '/index/',
    '/logout/',
    '/stark/dipay/customer/create/',
    '^/$',
    '/media/.*',
]

# 自动发现项目权限中要排除的路径
AUTO_DISCOVER_EXCLUDE = [
    '/admin/.*',
    '/admin\/.*',
    '/login/',
    '/logout/',
    '/index/',
]
##################  end of RBAC 设置 ###############


SESSION_COOKIE_AGE = 259200  # 用户的cookie存储最长时间3天，3天后必须重新登录


# Redis设置
CACHES = {
    'default' : {
    "BACKEND": 'django_redis.cache.RedisCache',
    "LOCATION": 'redis://0.0.0.0:6379',
    "OPTIONS" :{
        "CLIENT_CLASS" : "django_redis.client.DefaultClient",
        # "PASSWORD": '123',
    }
}
}

