# Generated by Django 3.2 on 2022-04-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='银行名')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='币种名')),
                ('icon', models.CharField(max_length=3, verbose_name='币种符号')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='客户名')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='邮箱')),
                ('nickname', models.CharField(max_length=30, verbose_name='姓名')),
                ('roles', models.ManyToManyField(blank=True, null=True, to='rbac.Role', verbose_name='角色')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='付款人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.customer', verbose_name='客户')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('goods', models.CharField(max_length=128, verbose_name='数量-货物')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='金额')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.currency', verbose_name='币种')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Inwardpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_created=True, verbose_name='汇入日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='金额')),
                ('status', models.SmallIntegerField(choices=[(0, '待关联'), (1, '已关联')], verbose_name='状态')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.bank', verbose_name='收款行')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.currency', verbose_name='币种')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.payer', verbose_name='付款人')),
            ],
        ),
    ]
