# Generated by Django 3.2 on 2022-06-16 13:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0002_menu_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='申请日期')),
                ('confirm_date', models.DateField(blank=True, null=True, verbose_name='下单日期')),
                ('order_type', models.SmallIntegerField(choices=[(0, 'J'), (1, 'M'), (2, 'X')], verbose_name='订单类型')),
                ('order_number', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='订单号')),
                ('sequence', models.IntegerField(blank=True, null=True, verbose_name='订单序号')),
                ('sub_sequence', models.IntegerField(default=0, verbose_name='分批号')),
                ('goods', models.CharField(max_length=128, verbose_name='数量-货物')),
                ('remark', models.TextField(default='--', verbose_name='详情')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='发票金额')),
                ('rcvd_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='到账金额')),
                ('collect_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='应收金额')),
                ('term', models.SmallIntegerField(choices=[(0, 'FOB'), (1, 'CFR'), (2, 'CIF'), (3, 'EXW')], default=0, verbose_name='贸易条款')),
                ('status', models.SmallIntegerField(choices=[(0, '申请中'), (1, '已配单号'), (2, '已下单'), (3, '完结'), (4, '固定账户'), (5, '无效')], default=0, verbose_name='订单状态')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='银行名')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='AuthorName')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='币种名')),
                ('icon', models.CharField(max_length=3, verbose_name='币种符号')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='序号')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='客户名')),
                ('shortname', models.CharField(default='-', max_length=20, verbose_name='客户简称')),
            ],
        ),
        migrations.CreateModel(
            name='Inwardpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(default=datetime.datetime(2022, 6, 16, 13, 37, 46, 599382), verbose_name='汇入日期')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='水单金额')),
                ('got_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='实收金额')),
                ('torelate_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='待关联金额')),
                ('status', models.SmallIntegerField(choices=[(0, '待关联'), (1, '已关联')], default=0, verbose_name='状态')),
                ('confirm_status', models.SmallIntegerField(choices=[(0, '未确认'), (1, '业务确认'), (2, '跟单确认'), (4, '财务确认'), (3, '业务.跟单确认'), (5, '业务.财务确认'), (6, '跟单.财务确认'), (7, '全部确认')], default=0, verbose_name='确认')),
                ('remark', models.TextField(default='-', verbose_name='备注')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.bank', verbose_name='收款行')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.currency', verbose_name='币种')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dipay.customer', verbose_name='客户')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='邮箱')),
                ('nickname', models.CharField(max_length=30, verbose_name='姓名')),
                ('department', models.SmallIntegerField(choices=[(1, '业务部'), (2, '跟单部'), (4, '财务部'), (8, '管理部')], default=1, verbose_name='部门')),
                ('roles', models.ManyToManyField(blank=True, null=True, to='rbac.Role', verbose_name='角色')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='付款人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.customer', verbose_name='客户')),
            ],
        ),
        migrations.CreateModel(
            name='Pay2Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relate_date', models.DateField(auto_now_add=True, verbose_name='关联日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='关联金额')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.applyorder', verbose_name='订单')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.inwardpay', verbose_name='收款')),
            ],
        ),
        migrations.AddField(
            model_name='inwardpay',
            name='keyin_user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='dipay.userinfo', verbose_name='录入人'),
        ),
        migrations.AddField(
            model_name='inwardpay',
            name='orders',
            field=models.ManyToManyField(blank=True, through='dipay.Pay2Orders', to='dipay.ApplyOrder', verbose_name='关联记录'),
        ),
        migrations.AddField(
            model_name='inwardpay',
            name='payer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dipay.payer', verbose_name='付款人'),
        ),
        migrations.CreateModel(
            name='FollowOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_port', models.CharField(default='Tianjin', max_length=32, verbose_name='起运港')),
                ('discharge_port', models.CharField(default='-', max_length=32, verbose_name='目的港')),
                ('ETD', models.DateField(blank=True, null=True, verbose_name='ETD')),
                ('ETA', models.DateField(blank=True, null=True, verbose_name='ETA')),
                ('book_info', models.CharField(default='订舱:', max_length=255, verbose_name='订舱信息')),
                ('load_info', models.CharField(default='装箱:', max_length=255, verbose_name='装箱信息')),
                ('produce_info', models.CharField(default='生产:', max_length=128, verbose_name='生产情况')),
                ('sales_remark', models.CharField(default='-', max_length=128, verbose_name='业务备注')),
                ('pay_term', models.SmallIntegerField(choices=[(0, '到港付'), (1, '出厂付'), (2, '预付')], default=1, verbose_name='付款方式')),
                ('status', models.SmallIntegerField(choices=[(0, '备货'), (1, '发货'), (5, '货好'), (2, '单据'), (3, '等款'), (4, '完成')], default=0, verbose_name='状态')),
                ('produce_sequence', models.SmallIntegerField(default=999, verbose_name='排产顺序')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dipay.applyorder', verbose_name='订单号')),
                ('salesperson', models.ForeignKey(limit_choices_to={'roles__title': '外销员'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dipay.userinfo', verbose_name='外销员')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'department': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dipay.userinfo', verbose_name='所属外销员'),
        ),
        migrations.AddField(
            model_name='applyorder',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dipay.currency', verbose_name='币种'),
        ),
        migrations.AddField(
            model_name='applyorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dipay.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='applyorder',
            name='salesperson',
            field=models.ForeignKey(limit_choices_to={'roles__title': '外销员'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dipay.userinfo', verbose_name='外销员'),
        ),
    ]
