# Generated by Django 3.2 on 2022-06-16 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 16, 13, 39, 39, 941237), verbose_name='汇入日期'),
        ),
    ]
