# Generated by Django 3.2 on 2022-04-26 04:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='下单日期'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='申请日期')),
                ('type', models.SmallIntegerField(choices=[(0, '待关联'), (1, '已关联')], verbose_name='订单类型')),
                ('sequence', models.IntegerField(verbose_name='订单序号')),
                ('goods', models.CharField(max_length=128, verbose_name='数量-货物')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.customer')),
            ],
        ),
    ]
