# Generated by Django 3.2 on 2022-04-26 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0002_auto_20220426_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='申请日期')),
                ('type', models.SmallIntegerField(choices=[(0, 'J'), (1, 'M'), (2, 'X')], verbose_name='订单类型')),
                ('sequence', models.IntegerField(verbose_name='订单序号')),
                ('goods', models.CharField(max_length=128, verbose_name='数量-货物')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='序号')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderNumber',
        ),
    ]
