# Generated by Django 3.2 on 2022-06-16 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0002_alter_inwardpay_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followorder',
            old_name='salesperson',
            new_name='salesman',
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 16, 13, 42, 20, 949715), verbose_name='汇入日期'),
        ),
    ]
