# Generated by Django 3.2 on 2022-06-19 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0003_auto_20220616_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardpay',
            name='reference',
            field=models.IntegerField(help_text='避免出现重复记录', null=True, verbose_name='收款编号'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 19, 3, 59, 42, 562871), verbose_name='汇入日期'),
        ),
    ]
