# Generated by Django 3.2 on 2022-06-19 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0004_auto_20220619_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followorder',
            old_name='salesperson',
            new_name='salesman',
        ),
        migrations.AddField(
            model_name='currentnumber',
            name='reference',
            field=models.IntegerField(default=3, verbose_name='收款编号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 19, 4, 21, 0, 572991), verbose_name='汇入日期'),
        ),
    ]
