# Generated by Django 3.2 on 2022-04-26 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0004_alter_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyorder',
            old_name='type',
            new_name='order_type',
        ),
    ]
