# Generated by Django 3.2 on 2022-04-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0005_rename_type_applyorder_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='订单号'),
        ),
    ]
