# Generated by Django 3.2 on 2022-04-27 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0006_applyorder_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyorder',
            name='remark',
            field=models.TextField(default='--', verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='applyorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.customer', verbose_name='客户'),
        ),
    ]
