# Generated by Django 3.2 on 2022-06-19 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0006_auto_20220619_0557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pay2orders',
            old_name='record_num',
            new_name='dist_ref',
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 19, 6, 3, 9, 328021), verbose_name='汇入日期'),
        ),
    ]
