# Generated by Django 3.2 on 2022-04-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0007_auto_20220427_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyorder',
            name='sequence',
            field=models.IntegerField(unique=True, verbose_name='订单序号'),
        ),
    ]
