# Generated by Django 3.2 on 2022-04-27 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0008_alter_applyorder_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyorder',
            name='salesperson',
            field=models.ForeignKey(limit_choices_to={'roles__title': '外销员'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dipay.userinfo', verbose_name='外销员'),
        ),
    ]
