# Generated by Django 3.2 on 2022-06-19 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0008_alter_inwardpay_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 19, 6, 45, 57, 923285), verbose_name='汇入日期'),
        ),
    ]
