# Generated by Django 3.2 on 2022-04-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0009_applyorder_salesperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='汇入日期'),
        ),
    ]
