# Generated by Django 3.2 on 2022-06-23 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0009_alter_inwardpay_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentnumber',
            name='dist_ref',
            field=models.IntegerField(default=6000, verbose_name='款项分配编号'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 23, 0, 47, 49, 662772), verbose_name='汇入日期'),
        ),
    ]
