# Generated by Django 3.2 on 2022-06-24 07:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0010_auto_20220623_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyorder',
            name='order_type',
            field=models.SmallIntegerField(choices=[(0, 'J'), (1, 'M'), (2, 'X'), (3, 'D')], verbose_name='订单类型'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 24, 7, 25, 18, 88272), verbose_name='汇入日期'),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('rate', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='汇率')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.currency', verbose_name='货币')),
            ],
        ),
    ]
