# Generated by Django 3.2 on 2022-05-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0010_alter_inwardpay_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='title',
            field=models.CharField(max_length=128, verbose_name='付款人'),
        ),
    ]
