# Generated by Django 3.2 on 2022-06-23 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0010_auto_20220623_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyorder',
            name='order_type',
            field=models.SmallIntegerField(choices=[(0, 'J'), (1, 'M'), (2, 'X'), (3, 'D')], verbose_name='订单类型'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 23, 6, 2, 47, 49962), verbose_name='汇入日期'),
        ),
    ]
