# Generated by Django 3.2 on 2022-05-02 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0011_alter_payer_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_port', models.CharField(default='Tianjin', max_length=32, verbose_name='起运港')),
                ('discharge_port', models.CharField(max_length=32, verbose_name='目的港')),
                ('ETD', models.DateField(blank=True, null=True, verbose_name='提单日期')),
                ('ETA', models.DateField(blank=True, null=True, verbose_name='到港日期')),
                ('book_agent', models.CharField(max_length=32, verbose_name='订舱代理')),
                ('load_agent', models.CharField(max_length=32, verbose_name='报关代理')),
                ('booking', models.CharField(default='海运费 / ', max_length=128, verbose_name='订舱')),
                ('remark', models.TextField(default='备注：', verbose_name='备注')),
                ('factory_remark', models.TextField(default='工厂备注：', verbose_name='工厂备注')),
                ('pay_term', models.SmallIntegerField(choices=[(0, '出厂付'), (1, '到港付'), (2, '赊销')], default=1, verbose_name='付款方式')),
            ],
        ),
        migrations.AddField(
            model_name='applyorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='金额'),
        ),
        migrations.AddField(
            model_name='applyorder',
            name='confirm_date',
            field=models.DateField(blank=True, null=True, verbose_name='下单日期'),
        ),
        migrations.AddField(
            model_name='applyorder',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dipay.currency', verbose_name='币种'),
        ),
        migrations.AddField(
            model_name='applyorder',
            name='term',
            field=models.SmallIntegerField(choices=[(0, 'FOB'), (1, 'CFR'), (2, 'CIF')], default=0, verbose_name='贸易条款'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='followorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.applyorder', verbose_name='订单号'),
        ),
    ]
