# Generated by Django 3.2 on 2022-06-26 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0012_auto_20220624_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='-', max_length=128, verbose_name='邮件地址'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 26, 2, 55, 59, 396717), verbose_name='汇入日期'),
        ),
    ]
