# Generated by Django 3.2 on 2022-05-02 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0012_auto_20220502_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyorder',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '待确认'), (1, '已下单'), (2, '完结')], default=0, verbose_name='下单状态'),
        ),
        migrations.AlterField(
            model_name='applyorder',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dipay.currency', verbose_name='币种'),
        ),
    ]
