# Generated by Django 3.2 on 2022-06-29 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0013_auto_20220626_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardpay',
            name='ttcopy',
            field=models.ImageField(blank=True, null=True, upload_to='ttcopy', verbose_name='电汇水单'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 29, 0, 45, 46, 632045), verbose_name='汇入日期'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='reference',
            field=models.IntegerField(default=1000, help_text='避免出现重复记录', null=True, verbose_name='收款编号'),
        ),
    ]
