# Generated by Django 3.2 on 2022-06-30 14:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0014_auto_20220629_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyorder',
            name='order_type',
            field=models.SmallIntegerField(choices=[(0, 'J'), (1, 'M'), (2, 'X'), (3, 'D'), (4, 'L')], verbose_name='订单类型'),
        ),
        migrations.AlterField(
            model_name='applyorder',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '申请中'), (1, '已配单号'), (2, '已下单'), (6, '款齐'), (3, '完结'), (4, '固定账户'), (5, '无效')], default=0, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 14, 8, 36, 480210), verbose_name='汇入日期'),
        ),
        migrations.CreateModel(
            name='ApplyRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateField(auto_now_add=True, verbose_name='申请日期')),
                ('verify_date', models.DateField(blank=True, null=True, verbose_name='审批日期')),
                ('remark', models.TextField(default='-', verbose_name='意见')),
                ('decision', models.BooleanField(null=True, verbose_name='审批结果')),
                ('applier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applier', to='dipay.userinfo', verbose_name='申请人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.applyorder', verbose_name='订单')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifier', to='dipay.userinfo', verbose_name='审批人')),
            ],
        ),
    ]
