# Generated by Django 3.2 on 2022-07-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0015_auto_20220630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyrelease',
            name='decision',
            field=models.BooleanField(null=True, verbose_name='审批意见'),
        ),
        migrations.AlterField(
            model_name='applyrelease',
            name='remark',
            field=models.TextField(default='-', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(verbose_name='汇入日期'),
        ),
    ]
