# Generated by Django 3.2 on 2022-05-03 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0016_inwardpay_torelate_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay2Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relate_date', models.DateField(auto_now_add=True, verbose_name='关联日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='关联金额')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.applyorder', verbose_name='订单')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.inwardpay', verbose_name='收款')),
            ],
        ),
        migrations.AddField(
            model_name='inwardpay',
            name='orders',
            field=models.ManyToManyField(through='dipay.Pay2Orders', to='dipay.ApplyOrder', verbose_name='关联记录'),
        ),
    ]
