# Generated by Django 3.2 on 2022-05-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0017_auto_20220503_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyorder',
            name='collect_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='应收金额'),
        ),
    ]
