# Generated by Django 3.2 on 2022-07-28 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0017_alter_inwardpay_ttcopy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='船公司全名')),
                ('shortname', models.CharField(max_length=30, verbose_name='船公司简称')),
                ('link', models.CharField(max_length=128, verbose_name='网址')),
            ],
        ),
        # migrations.AddField(
        #     model_name='followorder',
        #     name='container',
        #     field=models.CharField(default='--', max_length=20, verbose_name='生产情况'),
        # ),
        migrations.AddField(
            model_name='followorder',
            name='shipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dipay.shiplines', verbose_name='船公司'),
        ),
    ]
