# Generated by Django 3.2 on 2022-07-28 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0018_auto_20220728_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followorder',
            name='shipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dipay.shiplines', verbose_name='船公司'),
        ),
    ]
