# Generated by Django 3.2 on 2022-05-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0018_applyorder_collect_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardpay',
            name='got_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='实收金额'),
        ),
    ]
