# Generated by Django 3.2 on 2022-07-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0019_alter_followorder_shipline'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='followorder',
        #     name='container',
        #     field=models.CharField(default='--', max_length=20, verbose_name='生产情况'),
        # ),
        migrations.AlterField(
            model_name='followorder',
            name='book_info',
            field=models.CharField(default='订舱:', max_length=512, verbose_name='订舱信息'),
        ),
        migrations.AlterField(
            model_name='followorder',
            name='load_info',
            field=models.CharField(default='装箱:', max_length=512, verbose_name='装箱信息'),
        ),
    ]
