# Generated by Django 3.2.13 on 2022-05-08 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0019_inwardpay_got_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardpay',
            name='confirm_status',
            field=models.SmallIntegerField(choices=[(0, '未确认'), (1, '业务确认'), (2, '跟单确认'), (4, '财务确认'), (3, '业务.跟单确认'), (5, '业务.财务确认'), (6, '跟单.财务确认'), (7, '全部确认')], default=0, verbose_name='确认'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='水单金额'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 8, 13, 13, 25, 583712), verbose_name='汇入日期'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='orders',
            field=models.ManyToManyField(blank=True, through='dipay.Pay2Orders', to='dipay.ApplyOrder', verbose_name='关联记录'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '待关联'), (1, '已关联')], default=0, verbose_name='状态'),
        ),
    ]
