# Generated by Django 3.2 on 2022-09-02 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0020_auto_20220731_2338'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='followorder',
        #     name='container',
        #     field=models.CharField(default='--', max_length=20, verbose_name='生产情况'),
        # ),
        # migrations.AlterField(
        #     model_name='applyorder',
        #     name='order_type',
        #     field=models.SmallIntegerField(choices=[(0, 'J'), (1, 'M'), (2, 'X'), (3, 'D')], verbose_name='订单类型'),
        # ),
        # migrations.AlterField(
        #     model_name='followorder',
        #     name='status',
        #     field=models.SmallIntegerField(choices=[(0, '备货'), (1, '发货'), (5, '装箱'), (2, '单据'), (3, '等款'), (4, '完成')], default=0, verbose_name='状态'),
        # ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('remind_date', models.DateField(blank=True, null=True, verbose_name='提醒日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('content', models.CharField(max_length=512, verbose_name='任务')),
                ('status', models.SmallIntegerField(choices=[(0, '进行'), (2, '完成')], default=0, verbose_name='状态')),
                ('sequence', models.IntegerField(default=0, verbose_name='排序')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.followorder', verbose_name='关联')),
            ],
        ),
    ]
