# Generated by Django 3.2.13 on 2022-05-08 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0020_auto_20220508_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='department',
            field=models.SmallIntegerField(choices=[(1, '业务部'), (2, '跟单部'), (4, '财务部')], default=0, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 8, 15, 12, 29, 450981), verbose_name='汇入日期'),
        ),
    ]
