# Generated by Django 3.2 on 2022-05-09 08:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0021_auto_20220508_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardpay',
            name='keyin_user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='dipay.userinfo', verbose_name='录入人'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 9, 8, 46, 7, 759724), verbose_name='汇入日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='department',
            field=models.SmallIntegerField(choices=[(1, '业务部'), (2, '跟单部'), (4, '财务部')], default=1, verbose_name='部门'),
        ),
    ]
