# Generated by Django 3.2 on 2022-09-05 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0021_auto_20220902_0803'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='followorder',
        #     name='container',
        #     field=models.CharField(default='--', max_length=20, verbose_name='生产情况'),
        # ),
        migrations.AlterField(
            model_name='applyorder',
            name='order_type',
            field=models.SmallIntegerField(choices=[(0, 'J'), (1, 'M'), (2, 'X'), (3, 'D')], verbose_name='订单类型'),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dipay.followorder', verbose_name='关联'),
        ),
        migrations.AlterField(
            model_name='followorder',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '备货'), (1, '发货'), (5, '装箱'), (2, '单据'), (3, '等款'), (4, '完成')], default=0, verbose_name='状态'),
        ),
    ]
