# Generated by Django 3.2 on 2022-09-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0022_auto_20220905_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='remark',
            field=models.TextField(default='-', verbose_name='备注'),
        ),
        # migrations.AddField(
        #     model_name='followorder',
        #     name='container',
        #     field=models.CharField(default='--', max_length=20, verbose_name='生产情况'),
        # ),
    ]
