# Generated by Django 3.2 on 2022-09-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0023_auto_20220906_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='dipay.userinfo', verbose_name='创建人'),
        ),
        # migrations.AddField(
        #     model_name='followorder',
        #     name='container',
        #     field=models.CharField(default='--', max_length=20, verbose_name='生产情况'),
        # ),
        migrations.AlterField(
            model_name='dailyplan',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '进行'), (1, '完成')], default=0, verbose_name='状态'),
        ),
    ]
