# Generated by Django 3.2 on 2022-05-09 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0024_auto_20220509_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'department': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dipay.userinfo', verbose_name='所属外销员'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 9, 13, 7, 19, 256141), verbose_name='汇入日期'),
        ),
    ]
