# Generated by Django 3.2 on 2022-09-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0024_auto_20220906_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='urgence',
            field=models.BooleanField(default=False, verbose_name='紧急'),
        ),
        # migrations.AddField(
        #     model_name='followorder',
        #     name='container',
        #     field=models.CharField(default='--', max_length=20, verbose_name='生产情况'),
        # ),
    ]
