# Generated by Django 3.2 on 2022-09-23 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0011_auto_20220623_0602'),
        ('dipay', '0025_auto_20220906_2100'),
    ]

    operations = [
    ]
