# Generated by Django 3.2 on 2022-05-13 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0026_auto_20220513_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shortname',
            field=models.CharField(default='-', max_length=20, verbose_name='客户简称'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 13, 12, 52, 30, 869689), verbose_name='汇入日期'),
        ),
    ]
