# Generated by Django 3.2 on 2022-10-14 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0026_merge_0011_auto_20220623_0602_0025_auto_20220906_2100'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Forwarder',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=128, unique=True, verbose_name='客户名')),
        #         ('shortname', models.CharField(max_length=20, verbose_name='客户简称')),
        #         ('contact', models.CharField(default='-', max_length=20, verbose_name='联系人')),
        #         ('phone', models.CharField(default='-', max_length=11, verbose_name='电话')),
        #         ('email', models.CharField(default='-', max_length=128, verbose_name='邮件地址')),
        #         ('bank_account', models.TextField(default='--', verbose_name='银行信息')),
        #         ('remark', models.TextField(default='--', verbose_name='客户详情')),
        #     ],
        # ),
        # migrations.AddField(
        #     model_name='followorder',
        #     name='container',
        #     field=models.CharField(default='--', max_length=20, verbose_name='生产情况'),
        # ),
        migrations.AlterField(
            model_name='applyorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dipay.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shortname',
            field=models.CharField(max_length=20, verbose_name='客户简称'),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='remind_date',
            field=models.DateField(blank=True, null=True, verbose_name='提醒日(选填)'),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='sequence',
            field=models.IntegerField(default=6, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='创建日'),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '进行'), (1, '完成'), (2, '提醒')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(verbose_name='汇入日期'),
        ),
        migrations.CreateModel(
            name='Chance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建日')),
                ('company', models.CharField(max_length=128, unique=True, verbose_name='公司名')),
                ('contact', models.CharField(max_length=128, verbose_name='联系人')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('email', models.EmailField(max_length=128, verbose_name='邮件')),
                ('remark', models.TextField(default='--', verbose_name='客户详情')),
                ('owner', models.ForeignKey(limit_choices_to={'department': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dipay.userinfo', verbose_name='跟进外销员')),
            ],
        ),
    ]
