# Generated by Django 3.2 on 2022-10-14 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0027_auto_20221014_2228'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Forwarder',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=128, unique=True, verbose_name='客户名')),
        #         ('shortname', models.CharField(max_length=20, verbose_name='客户简称')),
        #         ('contact', models.CharField(default='-', max_length=20, verbose_name='联系人')),
        #         ('phone', models.CharField(default='-', max_length=11, verbose_name='电话')),
        #         ('email', models.CharField(default='-', max_length=128, verbose_name='邮件地址')),
        #         ('bank_account', models.TextField(default='--', verbose_name='银行信息')),
        #         ('remark', models.TextField(default='--', verbose_name='客户详情')),
        #     ],
        # ),
        migrations.AddField(
            model_name='chance',
            name='channel',
            field=models.SmallIntegerField(choices=[(0, '阿里询盘'), (1, '阿里RFQ'), (2, '1688'), (3, '广交会'), (4, '其他')], default=0, verbose_name='获取渠道'),
        ),
        # migrations.AddField(
        #     model_name='followorder',
        #     name='container',
        #     field=models.CharField(default='--', max_length=20, verbose_name='生产情况'),
        # ),
        migrations.AlterField(
            model_name='chance',
            name='remark',
            field=models.TextField(default='--', verbose_name='详情'),
        ),
        migrations.CreateModel(
            name='FollowChance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建日')),
                ('remark', models.TextField(default='--', verbose_name='跟进记录')),
                ('chance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.chance', verbose_name='商机')),
            ],
        ),
    ]
