# Generated by Django 3.2 on 2022-05-16 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0028_auto_20220516_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyorder',
            name='sub_sequence',
            field=models.IntegerField(default=0, verbose_name='分批号'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 4, 23, 40, 191726), verbose_name='汇入日期'),
        ),
    ]
