# Generated by Django 3.2 on 2022-10-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0028_auto_20221014_2257'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Forwarder',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=128, unique=True, verbose_name='客户名')),
        #         ('shortname', models.CharField(max_length=20, verbose_name='客户简称')),
        #         ('contact', models.CharField(default='-', max_length=20, verbose_name='联系人')),
        #         ('phone', models.CharField(default='-', max_length=11, verbose_name='电话')),
        #         ('email', models.CharField(default='-', max_length=128, verbose_name='邮件地址')),
        #         ('bank_account', models.TextField(default='--', verbose_name='银行信息')),
        #         ('remark', models.TextField(default='--', verbose_name='客户详情')),
        #     ],
        # ),
        migrations.AddField(
            model_name='chance',
            name='category',
            field=models.SmallIntegerField(choices=[(0, '轻钢'), (1, '烤漆'), (2, '配件'), (3, '其他')], default=0, verbose_name='产品'),
        ),
        # migrations.AddField(
        #     model_name='followorder',
        #     name='container',
        #     field=models.CharField(default='--', max_length=20, verbose_name='生产情况'),
        # ),
        migrations.AlterField(
            model_name='chance',
            name='company',
            field=models.CharField(max_length=128, verbose_name='公司名'),
        ),
    ]
