# Generated by Django 3.2 on 2022-10-15 13:10

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0029_auto_20221015_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forwarder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='货代名')),
                ('shortname', models.CharField(max_length=20, verbose_name='货代简称')),
                ('contact', models.CharField(default='-', max_length=20, verbose_name='货代联系人')),
                ('phone', models.CharField(default='-', max_length=11, verbose_name='电话')),
                ('email', models.CharField(default='-', max_length=128, verbose_name='邮件地址')),
                ('bank_account', models.TextField(default='--', verbose_name='银行信息')),
                ('remark', models.TextField(default='--', verbose_name='货代详情')),
            ],
        ),
        migrations.AddField(
            model_name='followorder',
            name='container',
            field=models.CharField(default='--', max_length=20, verbose_name='生产情况'),
        ),
        migrations.AlterField(
            model_name='chance',
            name='email',
            field=models.EmailField(max_length=128, null=True, verbose_name='邮件'),
        ),
        migrations.AlterField(
            model_name='chance',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='电话'),
        ),

        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('seafreight_cost', models.IntegerField(default=0, verbose_name='海运费成本')),
                ('seafreight', models.IntegerField(default=0, verbose_name='海运费')),
                ('insuance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='保险费')),
                ('port_charge', models.IntegerField(default=0, verbose_name='港杂费')),
                ('trailer_charge', models.IntegerField(default=0, verbose_name='拖车费')),
                ('other_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='其他费用')),
                ('remark', models.TextField(default='--', verbose_name='费用说明')),
                ('status', models.BooleanField(default=False, verbose_name='结清状态')),
            ],
        ),
        # migrations.CreateModel(
        #     name='ChargePay',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('create_date', models.DateField(auto_now_add=True, verbose_name='支付日期')),
        #         ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
        #         ('tt_copy', models.ImageField(null=True, upload_to='ttcopy', verbose_name='付款水单')),
        #         ('remark', models.TextField(default='--', verbose_name='备注')),
        #         ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.forwarder',
        #                                     verbose_name='货代')),
        #         # ('bills', models.ManyToManyField(to='dipay.Charge', verbose_name='关联账单')),
        #         ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.currency',
        #                                        verbose_name='货币')),
        #         ('frombank',
        #          models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.bank', verbose_name='出账银行')),
        #     ],
        # ),
    ]
