# Generated by Django 3.2 on 2022-05-16 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0029_auto_20220516_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='applyorder',
            name='sequence',
            field=models.IntegerField(blank=True, null=True, verbose_name='订单序号'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 4, 26, 25, 297154), verbose_name='汇入日期'),
        ),
    ]
