# Generated by Django 3.2 on 2022-10-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0029_auto_20221015_0843'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Forwarder',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=128, unique=True, verbose_name='货代名')),
        #         ('shortname', models.CharField(max_length=20, verbose_name='货代简称')),
        #         ('contact', models.CharField(default='-', max_length=20, verbose_name='货代联系人')),
        #         ('phone', models.CharField(default='-', max_length=11, verbose_name='电话')),
        #         ('email', models.CharField(default='-', max_length=128, verbose_name='邮件地址')),
        #         ('bank_account', models.TextField(default='--', verbose_name='银行信息')),
        #         ('remark', models.TextField(default='--', verbose_name='货代详情')),
        #     ],
        # ),
        # migrations.AddField(
        #     model_name='followorder',
        #     name='container',
        #     field=models.CharField(default='--', max_length=20, verbose_name='生产情况'),
        # ),
        migrations.AlterField(
            model_name='chance',
            name='email',
            field=models.EmailField(max_length=128, null=True, verbose_name='邮件'),
        ),
        migrations.AlterField(
            model_name='chance',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='电话'),
        ),
    ]
