# Generated by Django 3.2 on 2022-05-17 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0030_auto_20220516_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='客户名'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 17, 0, 15, 27, 290583), verbose_name='汇入日期'),
        ),
    ]
