# Generated by Django 3.2 on 2022-05-22 13:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0031_auto_20220517_0015'),
    ]

    operations = [

    ]
