# Generated by Django 3.2 on 2022-05-22 13:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0031_auto_20220517_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followorder',
            name='book_agent',
        ),
        migrations.RemoveField(
            model_name='followorder',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='followorder',
            name='factory_remark',
        ),
        migrations.RemoveField(
            model_name='followorder',
            name='load_agent',
        ),
        migrations.RemoveField(
            model_name='followorder',
            name='remark',
        ),
        migrations.AddField(
            model_name='followorder',
            name='book_info',
            field=models.CharField(default='订舱:', max_length=128, verbose_name='订舱信息'),
        ),
        migrations.AddField(
            model_name='followorder',
            name='load_info',
            field=models.CharField(default='装箱:', max_length=128, verbose_name='装箱信息'),
        ),
        migrations.AddField(
            model_name='followorder',
            name='produce_info',
            field=models.CharField(default='生产:', max_length=128, verbose_name='生产情况'),
        ),
        migrations.AddField(
            model_name='followorder',
            name='produce_sequence',
            field=models.SmallIntegerField(default=999, verbose_name='排产顺序'),
        ),
        migrations.AddField(
            model_name='followorder',
            name='sales_remark',
            field=models.CharField(default='-', max_length=128, verbose_name='业务备注'),
        ),
        migrations.AddField(
            model_name='followorder',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '备货'), (1, '排产'), (2, '单据'), (3, '等款'), (4, '完成')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='followorder',
            name='ETA',
            field=models.DateField(blank=True, null=True, verbose_name='ETA'),
        ),
        migrations.AlterField(
            model_name='followorder',
            name='ETD',
            field=models.DateField(blank=True, null=True, verbose_name='ETD'),
        ),
        migrations.AlterField(
            model_name='followorder',
            name='discharge_port',
            field=models.CharField(default='-', max_length=32, verbose_name='目的港'),
        ),
        migrations.AlterField(
            model_name='followorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dipay.applyorder', verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='followorder',
            name='pay_term',
            field=models.SmallIntegerField(choices=[(0, '到港付'), (1, '出厂付'), (2, '预付')], default=1, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 22, 13, 27, 53, 966547), verbose_name='汇入日期'),
        ),
    ]
