# Generated by Django 3.2 on 2022-10-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0031_auto_20221020_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='seafreight_cost',
        ),
    ]
