# Generated by Django 3.2 on 2022-10-20 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0032_remove_charge_seafreight_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='支付日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('tt_copy', models.ImageField(null=True, upload_to='ttcopy', verbose_name='付款水单')),
                ('remark', models.TextField(default='--', verbose_name='备注')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.forwarder', verbose_name='货代')),
            ],
        ),
        migrations.CreateModel(
            name='PayToCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(default='--', verbose_name='备注')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.charge', verbose_name='费用单')),
                ('chargepay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.chargepay', verbose_name='付费单')),
            ],
        ),
        migrations.AddField(
            model_name='chargepay',
            name='bills',
            field=models.ManyToManyField(blank=True, through='dipay.PayToCharge', to='dipay.Charge', verbose_name='关联账单'),
        ),
        migrations.AddField(
            model_name='chargepay',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.currency', verbose_name='货币'),
        ),
        migrations.AddField(
            model_name='chargepay',
            name='frombank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.bank', verbose_name='出账银行'),
        ),
    ]
