# Generated by Django 3.2 on 2022-10-23 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0033_auto_20221020_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytocharge',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='金额'),
        ),
        migrations.AddField(
            model_name='paytocharge',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dipay.currency', verbose_name='货币'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='insuance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='保险费U$'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='other_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='其他费用￥'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='port_charge',
            field=models.IntegerField(default=0, verbose_name='港杂费￥'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='seafreight',
            field=models.IntegerField(default=0, verbose_name='海运费U$'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='trailer_charge',
            field=models.IntegerField(default=0, verbose_name='拖车费￥'),
        ),
        migrations.AlterField(
            model_name='chargepay',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dipay.currency', verbose_name='货币'),
        ),
    ]
