# Generated by Django 3.2 on 2022-10-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0034_auto_20221023_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未结'), (1, '美元已结'), (2, '人民币已结'), (3, '结清')], default=0, verbose_name='结清状态'),
        ),
    ]
