# Generated by Django 3.2 on 2022-10-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0035_alter_charge_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='other_charge',
            field=models.IntegerField(default=0, verbose_name='其他费用￥'),
        ),
    ]
