# Generated by Django 3.2 on 2022-10-23 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0036_alter_charge_other_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargepay',
            old_name='tt_copy',
            new_name='ttcopy',
        ),
    ]
