# Generated by Django 3.2 on 2022-10-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0037_rename_tt_copy_chargepay_ttcopy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargepay',
            old_name='bills',
            new_name='charges',
        ),
    ]
