# Generated by Django 3.2 on 2022-10-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0038_rename_bills_chargepay_charges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='insuance',
            new_name='insurance',
        ),
    ]
