# Generated by Django 3.2 on 2022-10-24 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0041_rename_agent_charge_forwarder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargepay',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dipay.bank', verbose_name='出账银行'),
        ),
        migrations.AlterField(
            model_name='chargepay',
            name='charge',
            field=models.ManyToManyField(blank=True, null=True, through='dipay.PayToCharge', to='dipay.Charge', verbose_name='关联账单'),
        ),
    ]
