# Generated by Django 3.2 on 2022-10-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0042_auto_20221024_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='followorder',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
