# Generated by Django 3.2 on 2022-10-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0043_followorder_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepay',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '待付'), (1, '已出账')], default=0, verbose_name='支付状态'),
        ),
    ]
