# Generated by Django 3.2 on 2022-10-29 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0044_chargepay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwarder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dipay.userinfo', verbose_name='绑定用户'),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='remind_date',
            field=models.DateField(blank=True, null=True, verbose_name='提醒'),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='开始'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='department',
            field=models.SmallIntegerField(choices=[(1, '业务部'), (2, '跟单部'), (4, '财务部'), (8, '管理部'), (7, '外部')], default=1, verbose_name='部门'),
        ),
    ]
