# Generated by Django 3.2 on 2022-10-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0045_auto_20221029_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='create_date',
        ),
        migrations.AddField(
            model_name='charge',
            name='BL_date',
            field=models.DateField(default='2022-10-01', verbose_name='提单日期'),
        ),
    ]
