# Generated by Django 3.2 on 2022-10-30 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0046_auto_20221029_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='remark',
            field=models.TextField(default='提单号 港口 箱量', verbose_name='费用说明'),
        ),
        migrations.AlterField(
            model_name='chargepay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 30, 16, 57, 54, 591163), verbose_name='支付日期'),
        ),
    ]
