# Generated by Django 3.2 on 2022-10-30 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0047_auto_20221030_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forwarder',
            name='user',
        ),
        migrations.AlterField(
            model_name='chargepay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 30, 17, 31, 53, 730330), verbose_name='支付日期'),
        ),
    ]
