# Generated by Django 3.2 on 2022-11-07 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0049_auto_20221030_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chance',
            name='phone',
            field=models.CharField(max_length=28, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='chargepay',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 7, 10, 37, 8, 885237), verbose_name='支付日期'),
        ),
    ]
