# Generated by Django 3.2 on 2022-12-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0050_auto_20221107_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwarder',
            name='is_option',
            field=models.BooleanField(default=False, verbose_name='加入筛选'),
        ),
        migrations.AlterField(
            model_name='chargepay',
            name='create_date',
            field=models.DateField(verbose_name='支付日期'),
        ),
    ]
