# Generated by Django 3.2 on 2022-12-03 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0051_auto_20221202_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='品名')),
                ('spec', models.CharField(max_length=128, verbose_name='规格')),
                ('thick', models.DecimalField(decimal_places=2, default=0.3, max_digits=10, verbose_name='厚度')),
                ('remark', models.TextField(default='--', verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='供应商名称')),
                ('contact', models.CharField(blank=True, max_length=128, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='电邮')),
                ('remark', models.TextField(default='--', verbose_name='备注')),
            ],
        ),
        migrations.AlterField(
            model_name='chargepay',
            name='charge',
            field=models.ManyToManyField(through='dipay.PayToCharge', to='dipay.Charge', verbose_name='关联账单'),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='价格')),
                ('vol', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='单只体积')),
                ('gw', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='单只重量')),
                ('remark', models.TextField(default='--', verbose_name='备注')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='dipay.product', verbose_name='产品')),
                ('supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dipay.supplier', verbose_name='供应商')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='quote',
            field=models.ManyToManyField(through='dipay.Quote', to='dipay.Supplier', verbose_name='报价单'),
        ),
    ]
