# Generated by Django 3.2 on 2022-12-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0053_auto_20221206_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplan',
            name='cc',
            field=models.ManyToManyField(blank=True, null=True, related_name='cc', to='dipay.UserInfo', verbose_name='抄送'),
        ),
    ]
