# Generated by Django 3.2 on 2022-12-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0054_alter_dailyplan_cc'),
    ]

    operations = [
        migrations.AddField(
            model_name='followorder',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='到港通知否'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='BL_date',
            field=models.DateField(verbose_name='提单日期'),
        ),
    ]
