# Generated by Django 3.2 on 2022-12-10 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0055_auto_20221209_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='港口名')),
            ],
        ),
        migrations.AddField(
            model_name='applyorder',
            name='discharge_port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dipay.ports', verbose_name='目的港'),
        ),
    ]
