# Generated by Django 3.2 on 2022-12-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0056_auto_20221210_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay2orders',
            name='rate',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=9, verbose_name='转换率'),
        ),
    ]
