# Generated by Django 3.2 on 2022-12-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0058_auto_20221223_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyorder',
            name='amount_check',
            field=models.BooleanField(default=False, verbose_name='发票金额确认否'),
        ),
        migrations.AlterField(
            model_name='pay2orders',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=9, verbose_name='转换率'),
        ),
    ]
