# Generated by Django 3.2 on 2023-01-29 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0059_auto_20221228_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='产品分组')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thick',
        ),
        migrations.AddField(
            model_name='product',
            name='title_English',
            field=models.CharField(max_length=128, null=True, verbose_name='英文品名'),
        ),
        migrations.AlterField(
            model_name='applyorder',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '申请中'), (1, '已配单号'), (2, '已下单'), (3, '完结')], default=0, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='forwarder',
            name='contact',
            field=models.CharField(default='-', max_length=20, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='forwarder',
            name='email',
            field=models.CharField(default='-', max_length=128, verbose_name='邮件'),
        ),
        migrations.AlterField(
            model_name='forwarder',
            name='is_option',
            field=models.BooleanField(default=False, verbose_name='筛选'),
        ),
        migrations.AlterField(
            model_name='forwarder',
            name='remark',
            field=models.TextField(default='--', verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='forwarder',
            name='shortname',
            field=models.CharField(max_length=20, verbose_name='简称'),
        ),
        migrations.CreateModel(
            name='ModelNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(max_length=128, verbose_name='规格')),
                ('thick', models.DecimalField(decimal_places=2, default=0.3, max_digits=10, verbose_name='厚度')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipay.product', verbose_name='品名')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dipay.catagory', verbose_name='组别'),
        ),
    ]
