# Generated by Django 3.2 on 2023-02-23 14:10

import dipay.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0060_auto_20230129_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargepay',
            name='ttcopy',
            field=models.ImageField(null=True, upload_to=dipay.models.getPath, verbose_name='付款水单'),
        ),
    ]
