# Generated by Django 3.2 on 2023-03-12 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0061_alter_chargepay_ttcopy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(blank=True, null=True, to='dipay.Supplier', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='quote',
            name='modelnumbers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='dipay.modelnumbers', verbose_name='型号'),
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='productphoto', verbose_name='产品图片')),
                ('ismain', models.BooleanField(default=False, verbose_name='是否主图')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dipay.product', verbose_name='产品')),
            ],
        ),
    ]
