# Generated by Django 3.2 on 2023-04-05 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0062_auto_20230312_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='gw',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='vol',
        ),
        migrations.AddField(
            model_name='modelnumbers',
            name='gw',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='单只重量'),
        ),
        migrations.AddField(
            model_name='modelnumbers',
            name='remark',
            field=models.TextField(default='--', verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='modelnumbers',
            name='vol',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='单只体积'),
        ),
        migrations.AddField(
            model_name='quote',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='报价日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelnumbers',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='参考价格'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='工厂报价'),
        ),
    ]
