# Generated by Django 3.2 on 2023-04-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0063_auto_20230405_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelnumbers',
            name='gw',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='单只重量'),
        ),
        migrations.AlterField(
            model_name='modelnumbers',
            name='vol',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='单只体积'),
        ),
    ]
