# Generated by Django 3.2 on 2024-02-11 05:52

import dipay.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0064_auto_20230405_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=9, verbose_name='汇率'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='ttcopy',
            field=models.ImageField(null=True, storage=dipay.utils.storage.ImageStorage(), upload_to='ttcopy', verbose_name='电汇水单'),
        ),
        migrations.AlterField(
            model_name='modelnumbers',
            name='thick',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='厚度'),
        ),
    ]
