# Generated by Django 3.2 on 2025-02-02 16:42

import dipay.models
import dipay.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0065_auto_20240211_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargepay',
            name='ttcopy',
            field=models.ImageField(null=True, storage=dipay.utils.storage.ImageStorage(pre_filename='fwd'), upload_to=dipay.models.getPath, verbose_name='付款水单'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='create_date',
            field=models.DateField(verbose_name='汇入出日期'),
        ),
        migrations.AlterField(
            model_name='inwardpay',
            name='ttcopy',
            field=models.ImageField(null=True, storage=dipay.utils.storage.ImageStorage(pre_filename='pay'), upload_to='ttcopy', verbose_name='电汇水单'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.ImageField(storage=dipay.utils.storage.ImageStorage(pre_filename='prod'), upload_to='productphoto', verbose_name='产品图片'),
        ),
    ]
