# Generated by Django 3.2 on 2026-09-05 08:45

import dipay.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipay', '0066_auto_20250203_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyorder',
            name='po_number',
            field=models.CharField(max_length=30, null=True, verbose_name='PO号'),
        ),
        migrations.AddField(
            model_name='bank',
            name='frequency',
            field=models.IntegerField(default=0, verbose_name='使用频率'),
        ),
        migrations.AddField(
            model_name='chargepay',
            name='fee_invoice',
            field=models.ImageField(null=True, storage=dipay.utils.storage.ImageStorage(pre_filename='inv'), upload_to='feeinvoice', verbose_name='费用发票'),
        ),
        migrations.AddField(
            model_name='customer',
            name='follow_id',
            field=models.CharField(max_length=20, null=True, verbose_name='followID'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='is_sms_sent',
            field=models.BooleanField(default=False, verbose_name='提醒短信已发送'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_onjob',
            field=models.BooleanField(default=True, verbose_name='在职状态'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='手机'),
        ),
    ]
