# Generated by Django 3.2 on 2022-04-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='一级菜单')),
                ('icon', models.CharField(max_length=30, null=True, verbose_name='图标')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='权限名')),
                ('name', models.CharField(max_length=128, null=True, unique=True, verbose_name='权限别名')),
                ('urls', models.CharField(max_length=128, verbose_name='权限URL')),
                ('icon', models.CharField(max_length=30, null=True, verbose_name='图标')),
                ('menu', models.ForeignKey(blank=True, help_text='null表示不是菜单', null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.menu', verbose_name='所属一级菜单')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.permission', verbose_name='父级菜单')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='角色名')),
                ('permissions', models.ManyToManyField(to='rbac.Permission', verbose_name='权限')),
            ],
        ),
    ]
