# Generated by Django 3.2 on 2022-05-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='sequence',
            field=models.SmallIntegerField(default=0, verbose_name='次序'),
        ),
    ]
