# Generated by Django 3.2 on 2022-06-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_menu_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='icon',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='图标'),
        ),
    ]
